export type MapSheetPlace = {
  id: string;
  contentId: string;
  contentTypeId: string;
  areaCode: string;
  signguCode: string;
  touristTrendName: string;
  topRank: number | null;
  title: string;
  address: string;
  lat: number;
  lng: number;
  contentTypeLabel: string;
  categoryName: string;
  categoryCode1?: string;
  categoryCode2?: string;
  categoryCode3?: string;
  verificationRadiusMeters?: number | null;
  extendedVerificationRequiresPhoto?: boolean | null;
  icon: string;
  images: string[];
  eventStartDate?: string;
  eventEndDate?: string;
};
