query LikedSharedRouteConnection(
  $regionTag: String
  $limit: Int
  $cursor: String
) {
  likedRouteConnection(regionTag: $regionTag, limit: $limit, cursor: $cursor) {
    nodes {
      ...RouteSummaryFields
      owner {
        ...SharedRouteOwnerFields
      }
      stops {
        id
        place {
          contentId
          contentTypeId
          title
          address
          categoryLabel
          categoryName
          regionCode
          regionLabelKey
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
