query SharedRouteConnection(
  $regionCode: String
  $regionTag: String
  $limit: Int
  $cursor: String
) {
  sharedRouteConnection(
    regionCode: $regionCode
    regionTag: $regionTag
    limit: $limit
    cursor: $cursor
  ) {
    nodes {
      ...RouteSummaryFields
      owner {
        ...SharedRouteOwnerFields
      }
      stops {
        id
        place {
          contentId
          contentTypeId
          title
          address
          categoryLabel
          categoryName
          regionCode
          regionLabelKey
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
